import { useNavigate } from "react-router-dom";

export default function Landing() {
  const navigate = useNavigate();

  return (
    <main className="min-h-screen bg-white">
      <section className="px-16 py-20 grid grid-cols-1 md:grid-cols-2 gap-16 items-center">
        <div>
          <h1 className="text-5xl font-extrabold text-blue-700 leading-tight">
            Voter<span className="text-blue-500">X</span>
          </h1>

          <h2 className="mt-4 text-3xl font-semibold text-gray-800">
            Blockchain-Based Secure Voting System
          </h2>

          <p className="mt-6 text-gray-600 text-lg">
            VoterX is a decentralized and tamper-proof voting platform
            built using Blockchain and MERN stack. It is designed for
            educational institutes and organizations to conduct
            secure, transparent, and verifiable elections.
          </p>

          <p className="mt-4 text-gray-600 text-lg">
            Institutes can request access to VoterX by contacting our
            team. Once approved, a dedicated admin account is created
            and credentials are securely delivered via email.
          </p>
          <div className="mt-8 flex space-x-4">
            <button
              onClick={() => navigate("/contact")}
              className="px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition"
            >
              Contact Us
            </button>

            <button
              onClick={() => navigate("/about_Us")}
              className="px-6 py-3 border-2 border-blue-600 text-blue-600 rounded-lg font-semibold hover:bg-blue-50 transition"
            >
              Learn More
            </button>
          </div>
        </div>
        <div className="flex justify-center">
          <div className="w-96 h-96 bg-blue-100 rounded-2xl flex flex-col items-center justify-center shadow-lg">
            <div className="text-6xl mb-6">🗳️</div>
            <p className="text-blue-700 text-xl font-semibold text-center px-6">
              Secure • Transparent • Decentralized
            </p>
          </div>
        </div>

      </section>
      <section className="bg-blue-50 px-16 py-20">
        <h2 className="text-3xl font-bold text-center text-blue-700">
          Why Institutes Choose VoterX
        </h2>

        <div className="mt-12 grid grid-cols-1 md:grid-cols-3 gap-10">
          <div className="bg-white p-6 rounded-xl shadow">
            <h3 className="text-xl font-semibold text-blue-600">
              Blockchain Security
            </h3>
            <p className="mt-3 text-gray-600">
              Votes are immutable and stored securely on the blockchain,
              eliminating tampering and fraud.
            </p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow">
            <h3 className="text-xl font-semibold text-blue-600">
              Institute-Specific Admin
            </h3>
            <p className="mt-3 text-gray-600">
              Each institute receives its own admin panel to manage
              elections, voters, and results.
            </p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow">
            <h3 className="text-xl font-semibold text-blue-600">
              Secure Credential Delivery
            </h3>
            <p className="mt-3 text-gray-600">
              Admin login credentials are generated by our team and
              securely delivered to the institute via official email.
            </p>
          </div>
        </div>
      </section>
      <footer className="bg-blue-600 text-white text-center py-4">
        © {new Date().getFullYear()} VoterX — Blockchain-Powered Voting System
      </footer>

    </main>
  );
}
